spring:
  application:
    name: tpm-machine-service
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5433/machine_db}
    username: ${SPRING_DATASOURCE_USERNAME:machine_user}
    password: ${SPRING_DATASOURCE_PASSWORD:machine}
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
  flyway:
    enabled: true

management:
  endpoints:
    web:
      exposure:
        include: health
